In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress
import json
import tkinter as tk
from tkinter import filedialog
from tkinter import messagebox

projects_path = "Resources/HazardMitigationAssistanceProjects.csv"
summary_path = "Resources/DisasterDeclarationsSummaries.csv"

project_data = pd.read_csv(projects_path)
summary_data = pd.read_csv(summary_path)

In [16]:
project_clean = project_data[["disasterNumber", "benefitCostRatio", "projectIdentifier", "projectType"]]
project_clean

,disasterNumber,benefitCostRatio,projectIdentifier,projectType
0,1971.0,1.371,DR-1971-0561-R,206.1: Safe Room (Tornado and Severe Wind Shel...
1,1971.0,1.371,DR-1971-0428-R,206.1: Safe Room (Tornado and Severe Wind Shel...
2,1971.0,4.460,DR-1971-0430-R,206.2: Safe Room (Tornado and Severe Wind Shel...
3,1971.0,0.000,DR-1971-0373-F,601.1: Generators
4,1971.0,3.097,DR-1971-0672-R,206.2: Safe Room (Tornado and Severe Wind Shel...
...,...,...,...,...
29187,5233.0,1.400,DR-5233-0011-R,206.1: Safe Room (Tornado and Severe Wind Shel...
29189,4086.0,5.969,DR-4086-0646-R,602.1: Other Equipment Purchase and Installation
29190,4243.0,1.532,DR-4243-0009-R,200.1: Acquisition of Private Real Property (S...
29192,4086.0,0.000,DR-4086-0647-R,202.2: Elevation of Private Structures - Coastal
29193,4339.0,5.830,DR-4339-0016-R,601.1: Generators

In [15]:
summary_clean = summary_data[[ "disasterNumber", "incidentType", "state"]]
summary_clean

       disasterNumber incidentType state
0                   1      Tornado    GA
1                   4      Tornado    MI
2                   3        Flood    LA
3                   6      Tornado    MI
4                   2      Tornado    TX
...               ...          ...   ...
59522            3533    Hurricane    FL
59523            3533    Hurricane    FL
59524            3533    Hurricane    FL
59525            3533    Hurricane    FL
59526            3533    Hurricane    FL

[59527 rows x 3 columns]

In [17]:
merge_df = pd.merge(project_clean,summary_clean, how="outer", on="disasterNumber")
merge_df

,disasterNumber,benefitCostRatio,projectIdentifier,projectType,incidentType,state
0,1971.0,1.371,DR-1971-0561-R,206.1: Safe Room (Tornado and Severe Wind Shel...,Severe Storm(s),AL
1,1971.0,1.371,DR-1971-0561-R,206.1: Safe Room (Tornado and Severe Wind Shel...,Severe Storm(s),AL
2,1971.0,1.371,DR-1971-0561-R,206.1: Safe Room (Tornado and Severe Wind Shel...,Severe Storm(s),AL
3,1971.0,1.371,DR-1971-0561-R,206.1: Safe Room (Tornado and Severe Wind Shel...,Severe Storm(s),AL
4,1971.0,1.371,DR-1971-0561-R,206.1: Safe Room (Tornado and Severe Wind Shel...,Severe Storm(s),AL
...,...,...,...,...,...,...
614637,3533.0,NaN,NaN,NaN,Hurricane,FL
614638,3533.0,NaN,NaN,NaN,Hurricane,FL
614639,3533.0,NaN,NaN,NaN,Hurricane,FL
614640,3533.0,NaN,NaN,NaN,Hurricane,FL
614641,3533.0,NaN,NaN,NaN,Hurricane,FL

In [21]:
merge_clean = merge_df.dropna(inplace=False)
merge_clean = merge_clean.drop_duplicates()
merge_clean

,disasterNumber,benefitCostRatio,projectIdentifier,projectType,incidentType,state
0,1971.0,1.371,DR-1971-0561-R,206.1: Safe Room (Tornado and Severe Wind Shel...,Severe Storm(s),AL
67,1971.0,1.371,DR-1971-0428-R,206.1: Safe Room (Tornado and Severe Wind Shel...,Severe Storm(s),AL
134,1971.0,4.460,DR-1971-0430-R,206.2: Safe Room (Tornado and Severe Wind Shel...,Severe Storm(s),AL
201,1971.0,0.000,DR-1971-0373-F,601.1: Generators,Severe Storm(s),AL
268,1971.0,3.097,DR-1971-0672-R,206.2: Safe Room (Tornado and Severe Wind Shel...,Severe Storm(s),AL
...,...,...,...,...,...,...
576003,4376.0,0.000,DR-4376-0005-R,202.1: Elevation of Private Structures - Riverine,Flood,MD
576005,4418.0,0.000,DR-4418-0001-M,700.1: Management Costs - Salaries; \n700.4: M...,Severe Storm(s),WA
576013,4385.0,0.000,DR-4385-0001-M,700.1: Management Costs - Salaries,Tornado,CT
576015,4378.0,3.062,DR-4378-0004-R,601.2: Generators - Regular,Severe Storm(s),WV
576022,4388.0,0.000,DR-4388-0002-R,904.1: Advanced Assistance,Flood,MT

In [25]:
by_disaster = merge_clean.groupby("disasterNumber")
merge_clean["projectIdentifier"].nunique()

16866

In [ ]:
test_disaster = merge_df[merge_df["disasterNumber"] == 1971.0]
test_disaster